name: Build Backend APIs

on: 
  push:
    paths-ignore:
    - "docs/**"
    branches:
    - master
    - release/*
  pull_request:
    paths-ignore:
    - "docs/**"
    branches:
    - master  

jobs:
  build-server:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2    
        
    - name: Build with Maven
      run: mvn clean package --file server/pom.xml -DskipTests
      
    - name: Build Docker Image 
      run: mvn spring-boot:build-image --file server/pom.xml -DskipTests  
      
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin  
      
    - name: Push Docker Image
      run: docker push hantsy/angular-spring-reactive-sample-server    
      
 